// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu9g6UR2JN19z-g-wF9Zi3aruy_sN-ghE',
    appId: '1:163077646942:web:c14e2861c418d9a6cee2cf',
    messagingSenderId: '163077646942',
    projectId: 'productpro-5eef6',
    authDomain: 'productpro-5eef6.firebaseapp.com',
    storageBucket: 'productpro-5eef6.appspot.com',
    measurementId: 'G-1VHM7H41CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApbm0o8-UgSpp9QOy7Rx90xZJUyR1yOsQ',
    appId: '1:163077646942:android:e486169aeef2ae65cee2cf',
    messagingSenderId: '163077646942',
    projectId: 'productpro-5eef6',
    storageBucket: 'productpro-5eef6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb-K0OKp1mvUQ_Lfu-uPRzYLbHzbKtS9U',
    appId: '1:163077646942:ios:b66bc6b8310c1caccee2cf',
    messagingSenderId: '163077646942',
    projectId: 'productpro-5eef6',
    storageBucket: 'productpro-5eef6.appspot.com',
    iosBundleId: 'com.example.adminpanelHardwarepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb-K0OKp1mvUQ_Lfu-uPRzYLbHzbKtS9U',
    appId: '1:163077646942:ios:11160e4f57d7c8f2cee2cf',
    messagingSenderId: '163077646942',
    projectId: 'productpro-5eef6',
    storageBucket: 'productpro-5eef6.appspot.com',
    iosBundleId: 'com.example.adminpanelHardwarepro.RunnerTests',
  );
}
